version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: teg-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teg-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  teg-network:
    driver: bridge 