CREATE TABLE IF NOT EXISTS countries (
    id VARCHAR(50) PRIMARY KEY
);

INSERT INTO countries (id) VALUES
('ALASKA'), ('CANADA'), ('GROENLANDIA'), ('OREGON'), ('TERRANOVA'), ('CALIFORNIA'), ('MEXICO'), ('NUEVA_YORK'), ('QUEBEC'),
('VENEZUELA'), ('COLOMBIA'), ('ECUADOR'), ('PERU'), ('BRASIL'), ('BOLIVIA'), ('ARGENTINA'), ('CHILE'), ('URUGUAY'),
('ISLANDIA'), ('GRAN_BRETANA'), ('ESPANA'), ('FRANCIA'), ('ALEMANIA'), ('ITALIA'), ('POLONIA'), ('UCRANIA'), ('RUSIA'),
('MARRUECOS'), ('EGIPTO'), ('LIBIA'), ('SUDAN'), ('ETIOPIA'), ('ZAIRE'), ('NIGERIA'), ('SUDAFRICA'),
('ARABIA'), ('INDIA'), ('CHINA'), ('MONGOLIA'), ('SIBERIA'), ('TAILANDIA'), ('JAPON'), ('COREA'),
('INDONESIA'), ('NUEVA_GUINEA'), ('AUSTRALIA'), ('NUEVA_ZELANDA'), ('TURQUIA'), ('IRAN'), ('ARABIA_SAUDITA');